model:
  name: resnet101
  num_classes: 11
  pretrained: true

train:
  batch_size: 4
  epochs: 20
  lr: 0.0001
  weight_decay: 0.0001
  step_size: 5
  gamma: 0.1

path:
  train_json: data/train.json
  val_json: data/valid.json
  train_images: data/train
  val_images: data/valid
  save_path: checkpoints/best_model.pth
