model:
  name: fasterrcnn_resnet50_fpn
  num_classes: 11

training:
  num_epochs: 50
  batch_size: 4
  learning_rate: 0.005
  weight_decay: 0.0005
  momentum: 0.9

data:
  train_json: data/train.json
  val_json: data/valid.json
  train_dir: data/train
  val_dir: data/valid
  test_dir: data/test

output:
  model_path: output/fasterrcnn_digit.pth
